columns:
  - name: ID
    type: string
    nullable: false
    unique: true

  - name: Source
    type: string
    nullable: true

  - name: Severity
    type: integer
    nullable: true
    min: 1
    max: 4

  - name: Start_Time
    type: timestamp
    nullable: false

  - name: End_Time
    type: timestamp
    nullable: true

  - name: Start_Lat
    type: double
    nullable: true

  - name: Start_Lng
    type: double
    nullable: true

  - name: End_Lat
    type: double
    nullable: true

  - name: End_Lng
    type: double
    nullable: true

  - name: Distance(mi)
    type: double
    nullable: true
    min: 0

  - name: Description
    type: string
    nullable: true
    trim: true

  - name: City
    type: string
    nullable: true
    trim: true

  - name: State
    type: string
    nullable: true

  - name: Zipcode
    type: integer
    nullable: true

  - name: Country
    type: string
    nullable: true

  - name: Temperature(F)
    type: double
    nullable: true

  - name: Precipitation(in)
    type: double
    nullable: true

  - name: Humidity(%)
    type: double
    nullable: true
    min: 0
    max: 100

  - name: Visibility(mi)
    type: double
    nullable: true
    min: 0

  - name: Weather_Condition
    type: string
    nullable: true

  - name: Amenity
    type: boolean
    nullable: true

  - name: Traffic_Signal
    type: boolean
    nullable: true

deduplication:
  keys:
    - ID
  order_by: Start_Time